class Admin {
  String name,
      phone,
      email,
      passcode,
      busname,
      regno,
      seatno,
      type,
      updepot,
      uptime,
      uptvtime,
      downdepot,
      downtime,
      downtvtime,
      status,
      ticketprice,
      busimage,
      statusReason;
  Admin({
    required this.name,
    required this.phone,
    required this.email,
    required this.passcode,
    required this.busname,
    required this.regno,
    required this.seatno,
    required this.type,
    required this.updepot,
    required this.uptime,
    required this.uptvtime,
    required this.downdepot,
    required this.downtime,
    required this.downtvtime,
    required this.status,
    required this.ticketprice,
    required this.busimage,
    this.statusReason = '',
  });
}
